 Dropna and Fillna

In [30]:
import pandas as pd 

var = pd.read_csv("/Users/prajwalsubedi/Desktop/Data science/Pandas code/online_store_sales.csv")
var

,order_id,customer_id,age,gender,city,product_category,order_amount,discount,order_date,rating
0,101,201,25.0,Male,Delhi,Electronics,45000.0,5000.0,2024-01-05,5.0
1,102,202,NaN,Female,Mumbai,Fashion,3500.0,NaN,2024-01-06,4.0
2,103,203,32.0,Male,NaN,Electronics,60000.0,8000.0,2024-01-07,5.0
3,104,204,45.0,Female,Pune,Home,NaN,2000.0,2024-01-07,3.0
4,105,205,NaN,Male,Bangalore,Fashion,4200.0,500.0,NaN,4.0
5,106,206,29.0,Female,Delhi,NaN,1200.0,NaN,2024-01-09,NaN
6,107,207,38.0,Male,Mumbai,Electronics,52000.0,6000.0,2024-01-10,5.0
7,108,208,NaN,Female,NaN,Home,8000.0,NaN,2024-01-11,2.0
8,109,209,41.0,Male,Chennai,Fashion,NaN,1000.0,2024-01-12,3.0
9,110,210,27.0,Female,Delhi,Electronics,48000.0,NaN,2024-01-13,4.0

In [31]:
var.head()

,order_id,customer_id,age,gender,city,product_category,order_amount,discount,order_date,rating
0,101,201,25.0,Male,Delhi,Electronics,45000.0,5000.0,2024-01-05,5.0
1,102,202,NaN,Female,Mumbai,Fashion,3500.0,NaN,2024-01-06,4.0
2,103,203,32.0,Male,NaN,Electronics,60000.0,8000.0,2024-01-07,5.0
3,104,204,45.0,Female,Pune,Home,NaN,2000.0,2024-01-07,3.0
4,105,205,NaN,Male,Bangalore,Fashion,4200.0,500.0,NaN,4.0

In [32]:
var.shape

(10, 10)

var.dropna(axis=0) axis =0 drops rows having missing value and 1 drops columns contains missing value

and also if there is nan value in whole row then it can be removed by 
var.dropna(how="all")

var.dropna(subset=["is_fraud"]) this removes the row of a columns whose contains numm value leaving other columns null value.

var.dropna(inplace=True)
var
it revomes all null value and create new dataset. Just displays the updated DataFrame.

thresh is used in pandas with dropna() to control how many non-missing values are required to keep a row or column.

    thresh = n gives the least number of rows having null values to be remove from dataset.

the dropna() method returns a new DataFrame, and will not change the original.
If you want to change the original DataFrame, use the inplace = True argument:

import pandas as pd

df = pd.read_csv('data.csv')

new_df = df.dropna()

print(new_df.to_string())

if we do df.dropna(inplace = True) it will not create new dataframe but it will remove all rows containing null values

In [33]:
var.dropna(thresh=2)
var.head(15)

,order_id,customer_id,age,gender,city,product_category,order_amount,discount,order_date,rating
0,101,201,25.0,Male,Delhi,Electronics,45000.0,5000.0,2024-01-05,5.0
1,102,202,NaN,Female,Mumbai,Fashion,3500.0,NaN,2024-01-06,4.0
2,103,203,32.0,Male,NaN,Electronics,60000.0,8000.0,2024-01-07,5.0
3,104,204,45.0,Female,Pune,Home,NaN,2000.0,2024-01-07,3.0
4,105,205,NaN,Male,Bangalore,Fashion,4200.0,500.0,NaN,4.0
5,106,206,29.0,Female,Delhi,NaN,1200.0,NaN,2024-01-09,NaN
6,107,207,38.0,Male,Mumbai,Electronics,52000.0,6000.0,2024-01-10,5.0
7,108,208,NaN,Female,NaN,Home,8000.0,NaN,2024-01-11,2.0
8,109,209,41.0,Male,Chennai,Fashion,NaN,1000.0,2024-01-12,3.0
9,110,210,27.0,Female,Delhi,Electronics,48000.0,NaN,2024-01-13,4.0

In [34]:
var

,order_id,customer_id,age,gender,city,product_category,order_amount,discount,order_date,rating
0,101,201,25.0,Male,Delhi,Electronics,45000.0,5000.0,2024-01-05,5.0
1,102,202,NaN,Female,Mumbai,Fashion,3500.0,NaN,2024-01-06,4.0
2,103,203,32.0,Male,NaN,Electronics,60000.0,8000.0,2024-01-07,5.0
3,104,204,45.0,Female,Pune,Home,NaN,2000.0,2024-01-07,3.0
4,105,205,NaN,Male,Bangalore,Fashion,4200.0,500.0,NaN,4.0
5,106,206,29.0,Female,Delhi,NaN,1200.0,NaN,2024-01-09,NaN
6,107,207,38.0,Male,Mumbai,Electronics,52000.0,6000.0,2024-01-10,5.0
7,108,208,NaN,Female,NaN,Home,8000.0,NaN,2024-01-11,2.0
8,109,209,41.0,Male,Chennai,Fashion,NaN,1000.0,2024-01-12,3.0
9,110,210,27.0,Female,Delhi,Electronics,48000.0,NaN,2024-01-13,4.0

Fillna is used to fill the nun value in the dataset 
it takes column as arguments as
fillna({"column_name":"replace string or value"})

In [35]:
var.fillna({"age":"below", "city":"Kawasoti"})

,order_id,customer_id,age,gender,city,product_category,order_amount,discount,order_date,rating
0,101,201,25.0,Male,Delhi,Electronics,45000.0,5000.0,2024-01-05,5.0
1,102,202,below,Female,Mumbai,Fashion,3500.0,NaN,2024-01-06,4.0
2,103,203,32.0,Male,Kawasoti,Electronics,60000.0,8000.0,2024-01-07,5.0
3,104,204,45.0,Female,Pune,Home,NaN,2000.0,2024-01-07,3.0
4,105,205,below,Male,Bangalore,Fashion,4200.0,500.0,NaN,4.0
5,106,206,29.0,Female,Delhi,NaN,1200.0,NaN,2024-01-09,NaN
6,107,207,38.0,Male,Mumbai,Electronics,52000.0,6000.0,2024-01-10,5.0
7,108,208,below,Female,Kawasoti,Home,8000.0,NaN,2024-01-11,2.0
8,109,209,41.0,Male,Chennai,Fashion,NaN,1000.0,2024-01-12,3.0
9,110,210,27.0,Female,Delhi,Electronics,48000.0,NaN,2024-01-13,4.0

In [36]:
method is used when the nan value need to be fill by previous value or future value 

method ="ffill" it is for value replaced by previous one
method = "bfill" it is for value replaced by next one

SyntaxError: invalid syntax (2113430020.py, line 1)

var.fillna(130, inplace = True)

it will replace all null values in the dataset.

In [37]:
var

,order_id,customer_id,age,gender,city,product_category,order_amount,discount,order_date,rating
0,101,201,25.0,Male,Delhi,Electronics,45000.0,5000.0,2024-01-05,5.0
1,102,202,NaN,Female,Mumbai,Fashion,3500.0,NaN,2024-01-06,4.0
2,103,203,32.0,Male,NaN,Electronics,60000.0,8000.0,2024-01-07,5.0
3,104,204,45.0,Female,Pune,Home,NaN,2000.0,2024-01-07,3.0
4,105,205,NaN,Male,Bangalore,Fashion,4200.0,500.0,NaN,4.0
5,106,206,29.0,Female,Delhi,NaN,1200.0,NaN,2024-01-09,NaN
6,107,207,38.0,Male,Mumbai,Electronics,52000.0,6000.0,2024-01-10,5.0
7,108,208,NaN,Female,NaN,Home,8000.0,NaN,2024-01-11,2.0
8,109,209,41.0,Male,Chennai,Fashion,NaN,1000.0,2024-01-12,3.0
9,110,210,27.0,Female,Delhi,Electronics,48000.0,NaN,2024-01-13,4.0

To only replace empty values for one column, specify the column name for the DataFrame:

df.fillna({"discount": 130}, inplace=True)

There are many different ways to replace the nan value in dataset above we get some good examples but they cannot be used in all dataset as some required specific sensitive value so we use
Mean, Median and mode 

Mean = It is the average value od the whole data of the particular column 
Median= it is the middle value of the datas
mode = it is most frequently used data in whole dataset

In [39]:
x = var["discount"].median()

var.fillna({"discount": x}, inplace=True)
var

,order_id,customer_id,age,gender,city,product_category,order_amount,discount,order_date,rating
0,101,201,25.0,Male,Delhi,Electronics,45000.0,5000.0,2024-01-05,5.0
1,102,202,NaN,Female,Mumbai,Fashion,3500.0,3500.0,2024-01-06,4.0
2,103,203,32.0,Male,NaN,Electronics,60000.0,8000.0,2024-01-07,5.0
3,104,204,45.0,Female,Pune,Home,NaN,2000.0,2024-01-07,3.0
4,105,205,NaN,Male,Bangalore,Fashion,4200.0,500.0,NaN,4.0
5,106,206,29.0,Female,Delhi,NaN,1200.0,3500.0,2024-01-09,NaN
6,107,207,38.0,Male,Mumbai,Electronics,52000.0,6000.0,2024-01-10,5.0
7,108,208,NaN,Female,NaN,Home,8000.0,3500.0,2024-01-11,2.0
8,109,209,41.0,Male,Chennai,Fashion,NaN,1000.0,2024-01-12,3.0
9,110,210,27.0,Female,Delhi,Electronics,48000.0,3500.0,2024-01-13,4.0

In [40]:
y= var["order_amount"].mean()

var.fillna({"order_amount": y}, inplace = True)
var

,order_id,customer_id,age,gender,city,product_category,order_amount,discount,order_date,rating
0,101,201,25.0,Male,Delhi,Electronics,45000.0,5000.0,2024-01-05,5.0
1,102,202,NaN,Female,Mumbai,Fashion,3500.0,3500.0,2024-01-06,4.0
2,103,203,32.0,Male,NaN,Electronics,60000.0,8000.0,2024-01-07,5.0
3,104,204,45.0,Female,Pune,Home,27737.5,2000.0,2024-01-07,3.0
4,105,205,NaN,Male,Bangalore,Fashion,4200.0,500.0,NaN,4.0
5,106,206,29.0,Female,Delhi,NaN,1200.0,3500.0,2024-01-09,NaN
6,107,207,38.0,Male,Mumbai,Electronics,52000.0,6000.0,2024-01-10,5.0
7,108,208,NaN,Female,NaN,Home,8000.0,3500.0,2024-01-11,2.0
8,109,209,41.0,Male,Chennai,Fashion,27737.5,1000.0,2024-01-12,3.0
9,110,210,27.0,Female,Delhi,Electronics,48000.0,3500.0,2024-01-13,4.0

In [42]:
z= var["city"].mode()[0]

var.fillna({"city":z}, inplace = True)
var

,order_id,customer_id,age,gender,city,product_category,order_amount,discount,order_date,rating
0,101,201,25.0,Male,Delhi,Electronics,45000.0,5000.0,2024-01-05,5.0
1,102,202,NaN,Female,Mumbai,Fashion,3500.0,3500.0,2024-01-06,4.0
2,103,203,32.0,Male,Delhi,Electronics,60000.0,8000.0,2024-01-07,5.0
3,104,204,45.0,Female,Pune,Home,27737.5,2000.0,2024-01-07,3.0
4,105,205,NaN,Male,Bangalore,Fashion,4200.0,500.0,NaN,4.0
5,106,206,29.0,Female,Delhi,NaN,1200.0,3500.0,2024-01-09,NaN
6,107,207,38.0,Male,Mumbai,Electronics,52000.0,6000.0,2024-01-10,5.0
7,108,208,NaN,Female,Delhi,Home,8000.0,3500.0,2024-01-11,2.0
8,109,209,41.0,Male,Chennai,Fashion,27737.5,1000.0,2024-01-12,3.0
9,110,210,27.0,Female,Delhi,Electronics,48000.0,3500.0,2024-01-13,4.0

If in dataset there is any format error then solve it using different function given by pandas its easy

Now if there is any data wrong inside the dataset then we can replace it or make it correct 

df.loc[index number, 'column name '] = Desired value

Now for small dataset it is very suitable to view data and change accordingly using above syntax but we usually worked with larger dataset so when we encounter wrong value in larger dataset we can set particular condition in that column and can change value if condition is satisfied.