# One Hot Encoding (Nominal Data)

In [56]:
import pandas as pd 
import numpy as np

In [57]:
df= pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/covid_dataset.csv',index_col=False)

In [58]:
df

     Age  Gender  Fever   Cough       City Has_Covid
0     56    Male  102.4    Mild     Mumbai        No
1     19  Female  101.6  Strong     Mumbai        No
2     76  Female  102.0    Mild    Kolkata        No
3     65    Male   99.7    Mild  Bangalore        No
4     25  Female  102.1    Mild      Delhi       Yes
..   ...     ...    ...     ...        ...       ...
995   41    Male  102.0    Mild     Mumbai        No
996   76  Female  100.9    Mild      Delhi        No
997   35    Male  100.6    Mild    Kolkata        No
998   13  Female   99.5    Mild    Kolkata       Yes
999   55  Female  102.7  Strong    Kolkata       Yes

[1000 rows x 6 columns]

In [59]:
df['City'].unique()

array(['Mumbai', 'Kolkata', 'Bangalore', 'Delhi'], dtype=object)

### If I have n categories, we need to remove 1 column for multicollinearity to remove the mathematical  relation between the columns.

In [60]:
# df = pd.get_dummies(df, columns=['City'], dtype=int)

In [61]:
df

     Age  Gender  Fever   Cough       City Has_Covid
0     56    Male  102.4    Mild     Mumbai        No
1     19  Female  101.6  Strong     Mumbai        No
2     76  Female  102.0    Mild    Kolkata        No
3     65    Male   99.7    Mild  Bangalore        No
4     25  Female  102.1    Mild      Delhi       Yes
..   ...     ...    ...     ...        ...       ...
995   41    Male  102.0    Mild     Mumbai        No
996   76  Female  100.9    Mild      Delhi        No
997   35    Male  100.6    Mild    Kolkata        No
998   13  Female   99.5    Mild    Kolkata       Yes
999   55  Female  102.7  Strong    Kolkata       Yes

[1000 rows x 6 columns]

In [62]:
ok = pd.get_dummies(df, columns=['City'], dtype=int, drop_first=True)
ok

,Age,Gender,Fever,Cough,Has_Covid,City_Delhi,City_Kolkata,City_Mumbai
0,56,Male,102.4,Mild,No,0,0,1
1,19,Female,101.6,Strong,No,0,0,1
2,76,Female,102.0,Mild,No,0,1,0
3,65,Male,99.7,Mild,No,0,0,0
4,25,Female,102.1,Mild,Yes,1,0,0
...,...,...,...,...,...,...,...,...
995,41,Male,102.0,Mild,No,0,0,1
996,76,Female,100.9,Mild,No,1,0,0
997,35,Male,100.6,Mild,No,0,1,0
998,13,Female,99.5,Mild,Yes,0,1,0
999,55,Female,102.7,Strong,Yes,0,1,0

# One hot encoding usin scikit learn

In [63]:
df.head()

   Age  Gender  Fever   Cough       City Has_Covid
0   56    Male  102.4    Mild     Mumbai        No
1   19  Female  101.6  Strong     Mumbai        No
2   76  Female  102.0    Mild    Kolkata        No
3   65    Male   99.7    Mild  Bangalore        No
4   25  Female  102.1    Mild      Delhi       Yes

In [64]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(df.iloc[:,0:5],df.iloc[:,-1],test_size=0.2,random_state=1)

In [65]:
x_train

     Age  Gender  Fever   Cough       City
382   66    Male  100.4  Strong  Bangalore
994    9    Male   99.7  Strong    Kolkata
982   10    Male   99.7    Mild      Delhi
47     6    Male  100.2  Strong    Kolkata
521   11    Male   98.2    Mild      Delhi
..   ...     ...    ...     ...        ...
767   18  Female   99.0    Mild  Bangalore
72    19    Male  100.6    Mild      Delhi
908   30  Female  102.8  Strong      Delhi
235   41    Male  101.5    Mild    Kolkata
37    11  Female  102.3    Mild     Mumbai

[800 rows x 5 columns]

In [66]:
y_train

382    Yes
994     No
982     No
47     Yes
521    Yes
      ...
767     No
72     Yes
908    Yes
235     No
37      No
Name: Has_Covid, Length: 800, dtype: object

In [67]:
from sklearn.preprocessing import OneHotEncoder

In [70]:
ohe= OneHotEncoder(drop='first',sparse_output=False)

In [73]:
x_train_new=ohe.fit_transform(x_train[['City']])

In [72]:
x_test_new=ohe.fit_transform(x_test[['City']])

In [75]:
np.hstack((x_train[['City']].values,x_train_new))

array([['Bangalore', 0.0, 0.0, 0.0],
       ['Kolkata', 0.0, 1.0, 0.0],
       ['Delhi', 1.0, 0.0, 0.0],
       ...,
       ['Delhi', 1.0, 0.0, 0.0],
       ['Kolkata', 0.0, 1.0, 0.0],
       ['Mumbai', 0.0, 0.0, 1.0]], shape=(800, 4), dtype=object)

In [76]:
df['City'].value_counts()

City
Delhi        277
Kolkata      255
Mumbai       239
Bangalore    229
Name: count, dtype: int64

In [82]:
dff=pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/sample_store.csv',encoding='ISO-8859-1')

In [89]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [94]:
# dff['City'].nunique()
# dff['State'].nunique()
counts= dff['State'].value_counts()

In [96]:
dff['State'].nunique()
threshold =100

In [98]:
repl=counts[counts<=threshold].index

In [100]:
pd.get_dummies(dff['State'].replace(repl,'uncommon'),dtype=int)

,Arizona,California,Colorado,Florida,Georgia,Illinois,Indiana,Kentucky,Maryland,Massachusetts,...,North Carolina,Ohio,Oregon,Pennsylvania,Tennessee,Texas,Virginia,Washington,Wisconsin,uncommon
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9990,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9991,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9992,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9993,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0