In [82]:
import pandas as pd 
import numpy as np

In [83]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

In [84]:
df=pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/covid_dataset.csv')

In [85]:
df.head()

   Age  Gender  Fever   Cough       City Has_Covid
0   56    Male  102.4    Mild     Mumbai        No
1   19  Female  101.6  Strong     Mumbai        No
2   76  Female  102.0    Mild    Kolkata        No
3   65    Male   99.7    Mild  Bangalore        No
4   25  Female  102.1    Mild      Delhi       Yes

In [86]:
df.isnull().sum()

Age          0
Gender       0
Fever        0
Cough        0
City         0
Has_Covid    0
dtype: int64

In [87]:
x_train, x_test, y_train, y_test= train_test_split(df.drop(columns=['Has_Covid']),df['Has_Covid'],test_size=0.2,random_state=40)

In [88]:
x_train.head()

     Age  Gender  Fever   Cough       City
970    6  Female  101.0  Strong  Bangalore
137   75    Male  101.4  Strong     Mumbai
82    45  Female   98.7    Mild     Mumbai
188   48    Male   98.4  Strong      Delhi
358   46    Male  100.5    Mild      Delhi

In [89]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, MinMaxScaler

preprocessor = ColumnTransformer([
    
    # One-hot encode City (column 4)
    ('ohe_city', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [4]),

    # Ordinal encode Cough (column 3)
    ('oe_cough', OrdinalEncoder(categories=[['Mild', 'Strong']]), [3]),

    # Ordinal encode Gender (column 1)
    ('oe_gender', OrdinalEncoder(categories=[['Male', 'Female']]), [1]),

    # Scale numeric columns
    ('scale', MinMaxScaler(), [0, 2])  # adjust based on your dataset

], remainder='passthrough')

In [90]:
# one hot encoding 
# trf1 = ColumnTransformer([
#     ('ohe_city',OneHotEncoder(sparse_output=False, handle_unknown='ignore'),[4])
# ],remainder='passthrough')

In [91]:
# trf2 = ColumnTransformer(transformers=[
#     ('oe_cough_gender',OrdinalEncoder(categories=[['Mild','Strong'],['Male','Female']]),[3,1]),
# ],remainder='passthrough')

In [92]:
# trf3 = ColumnTransformer(transformers=[
#     ('le_Has_covid',LabelEncoder(),[5])
# ])

In [93]:
# trf4 = ColumnTransformer(transformers=[
#     ('scale',MinMaxScaler(),slice(0,10))
# ])

In [94]:
trf5= SelectKBest(score_func=chi2,k=8)

In [95]:
trf6= DecisionTreeClassifier()

# Creating Pipeline

In [96]:
pipe = Pipeline([
    ('preprocessor',preprocessor),
    ('trf5',trf5),
    ('trf6',trf6)
])

In [97]:
# pipe = Pipeline([
#     ('trf1',trf1),
#     ('trf2',trf2),
#     ('trf3',trf3),
#     ('trf4',trf4),
#     ('trf5',trf5),
#     ('trf6',trf6)
# ])

# Pipeline Vs make_pipeline

### pipeline require naming of steps where make_pipeline doesnt.

In [98]:
# pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5,trf6)

In [99]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_city',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [4]),
                                                 ('oe_cough',
                                                  OrdinalEncoder(categories=[['Mild',
                                                                              'Strong']]),
                                                  [3]),
                                                 ('oe_gender',
                                                  OrdinalEncoder(categories=[['Male',
                                                                              'Female']]),
                                                  [1]),
                                                 ('scale', MinMaxScaler(),
                                                  [0, 2])])),
                ('trf5',
                 SelectKBest(k=8, score_func=<function chi2 at 0x17af98f40>)),
                ('trf6', DecisionTreeClassifier())])

In [100]:
pipe.named_steps

{'preprocessor': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_city',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [4]),
                                 ('oe_cough',
                                  OrdinalEncoder(categories=[['Mild',
                                                              'Strong']]),
                                  [3]),
                                 ('oe_gender',
                                  OrdinalEncoder(categories=[['Male',
                                                              'Female']]),
                                  [1]),
                                 ('scale', MinMaxScaler(), [0, 2])]),
 'trf5': SelectKBest(k=8, score_func=<function chi2 at 0x17af98f40>),
 'trf6': DecisionTreeClassifier()}

In [101]:
y_pred =pipe.predict(x_test)

In [102]:
y_pred

array(['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes',
       'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No',
       'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No',
       'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No',
       'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes',
       'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes',
       'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
       'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No',
       'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No',
       'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
       'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
      dtype=object)

In [103]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.45

# Cross validation using Pipeline

In [104]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe,x_train,y_train,cv=5, scoring='accuracy').mean()

np.float64(0.48374999999999996)

In [105]:
# GridSearch using Pipeline

In [106]:
params ={
    'trf6__max_depth':[1,2,3,4,5,None]
}

In [107]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(x_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_city',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         [4]),
                                                                        ('oe_cough',
                                                                         OrdinalEncoder(categories=[['Mild',
                                                                                                     'Strong']]),
                                                                         [3]),
                                                                        ('oe_gender',
                                                                         OrdinalEncoder(categories=[['Male',
                                                                                                     'Female']]),
                                                                         [1]),
                                                                        ('scale',
                                                                         MinMaxScaler(),
                                                                         [0,
                                                                          2])])),
                                       ('trf5',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x17af98f40>)),
                                       ('trf6', DecisionTreeClassifier())]),
             param_grid={'trf6__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='accuracy')

In [108]:
grid.best_score_

np.float64(0.5)

In [109]:
grid.best_params_

{'trf6__max_depth': 1}

# Exporting the pipeline

In [110]:
import pickle
pickle.dump(pipe, open('pipe.pkl','wb'))

In [111]:
x_train

     Age  Gender  Fever   Cough       City
970    6  Female  101.0  Strong  Bangalore
137   75    Male  101.4  Strong     Mumbai
82    45  Female   98.7    Mild     Mumbai
188   48    Male   98.4  Strong      Delhi
358   46    Male  100.5    Mild      Delhi
..   ...     ...    ...     ...        ...
440   16  Female  100.4  Strong    Kolkata
165   48  Female  100.8  Strong    Kolkata
7     28    Male  100.7    Mild     Mumbai
219   43    Male  100.4    Mild    Kolkata
326   43    Male   99.7    Mild    Kolkata

[800 rows x 5 columns]