In [75]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [76]:
df = pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/sample_store.csv',encoding='iso-8859-1',usecols=['Order ID', 'Customer ID', 'Order Date'])

In [77]:
df.head(5)

         Order ID  Order Date Customer ID
0  CA-2016-152156   11/8/2016    CG-12520
1  CA-2016-152156   11/8/2016    CG-12520
2  CA-2016-138688   6/12/2016    DV-13045
3  US-2015-108966  10/11/2015    SO-20335
4  US-2015-108966  10/11/2015    SO-20335

In [78]:
df['Customer ID'].nunique()

793

In [79]:
df['Order ID'].nunique()

5009

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     9994 non-null   object
 1   Order Date   9994 non-null   object
 2   Customer ID  9994 non-null   object
dtypes: object(3)
memory usage: 234.4+ KB

# Handeling mixed variables

### If any columns as seperate numerical and categorical columns then we can use it.

In [81]:
# df['Customer ID_numerical']=pd.to_numeric(df["Customer ID"],errors='coerce',downcast='integer')

In [82]:
# df['Customer_ID_categorical']=np.where(df['Customer ID_numerical'].isnull(),df['Customer ID'],np.nan)

In [83]:
df.head()

         Order ID  Order Date Customer ID
0  CA-2016-152156   11/8/2016    CG-12520
1  CA-2016-152156   11/8/2016    CG-12520
2  CA-2016-138688   6/12/2016    DV-13045
3  US-2015-108966  10/11/2015    SO-20335
4  US-2015-108966  10/11/2015    SO-20335

In [84]:
# df['Customer ID_num']=df['Customer ID'].str.extract('(\d+)')
# df['Customer ID_cat']=df['Customer ID'].str[0]

In [85]:
df.head()

         Order ID  Order Date Customer ID
0  CA-2016-152156   11/8/2016    CG-12520
1  CA-2016-152156   11/8/2016    CG-12520
2  CA-2016-138688   6/12/2016    DV-13045
3  US-2015-108966  10/11/2015    SO-20335
4  US-2015-108966  10/11/2015    SO-20335

In [86]:
df['Customer ID']

0       CG-12520
1       CG-12520
2       DV-13045
3       SO-20335
4       SO-20335
          ...
9989    TB-21400
9990    DB-13060
9991    DB-13060
9992    DB-13060
9993    CC-12220
Name: Customer ID, Length: 9994, dtype: object

### If the coulumns contains mixed value in same rows this can be done to split them into numeric and categories

In [87]:
df['Category'] = df['Customer ID'].str.split('-').str[0]
df['Number'] = df['Customer ID'].str.split('-').str[1].astype(int)

In [88]:
df.head()

         Order ID  Order Date Customer ID Category  Number
0  CA-2016-152156   11/8/2016    CG-12520       CG   12520
1  CA-2016-152156   11/8/2016    CG-12520       CG   12520
2  CA-2016-138688   6/12/2016    DV-13045       DV   13045
3  US-2015-108966  10/11/2015    SO-20335       SO   20335
4  US-2015-108966  10/11/2015    SO-20335       SO   20335

# Handeling dates

In [92]:
df['Order Date']= pd.to_datetime(df['Order Date'])

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     9994 non-null   object
 1   Order Date   9994 non-null   datetime64[ns]
 2   Customer ID  9994 non-null   object
 3   Category     9994 non-null   object
 4   Number       9994 non-null   int64
 5   Date_year    9994 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 468.6+ KB

## 1. Extract Year

In [94]:
df['Date_year'] = df['Order Date'].dt.year

In [95]:
df.head()

         Order ID Order Date Customer ID Category  Number  Date_year
0  CA-2016-152156 2016-11-08    CG-12520       CG   12520       2016
1  CA-2016-152156 2016-11-08    CG-12520       CG   12520       2016
2  CA-2016-138688 2016-06-12    DV-13045       DV   13045       2016
3  US-2015-108966 2015-10-11    SO-20335       SO   20335       2015
4  US-2015-108966 2015-10-11    SO-20335       SO   20335       2015

In [98]:
df['Date_month_no'] = df['Order Date'].dt.month
df.head(4)

         Order ID Order Date Customer ID  ... Date_year  Date_month  Date_month_no
0  CA-2016-152156 2016-11-08    CG-12520  ...      2016    November             11
1  CA-2016-152156 2016-11-08    CG-12520  ...      2016    November             11
2  CA-2016-138688 2016-06-12    DV-13045  ...      2016        June              6
3  US-2015-108966 2015-10-11    SO-20335  ...      2015     October             10

[4 rows x 8 columns]

In [99]:
df['Date_month'] = df['Order Date'].dt.month_name()
df.head(4)

         Order ID Order Date Customer ID  ... Date_year  Date_month  Date_month_no
0  CA-2016-152156 2016-11-08    CG-12520  ...      2016    November             11
1  CA-2016-152156 2016-11-08    CG-12520  ...      2016    November             11
2  CA-2016-138688 2016-06-12    DV-13045  ...      2016        June              6
3  US-2015-108966 2015-10-11    SO-20335  ...      2015     October             10

[4 rows x 8 columns]

In [100]:
df['Date_day'] = df['Order Date'].dt.day
df.head(4)

         Order ID Order Date Customer ID  ... Date_month  Date_month_no  Date_day
0  CA-2016-152156 2016-11-08    CG-12520  ...   November             11         8
1  CA-2016-152156 2016-11-08    CG-12520  ...   November             11         8
2  CA-2016-138688 2016-06-12    DV-13045  ...       June              6        12
3  US-2015-108966 2015-10-11    SO-20335  ...    October             10        11

[4 rows x 9 columns]

In [104]:
df['Date_dayofweek_no'] = df['Order Date'].dt.dayofweek
df.head(4)

         Order ID Order Date  ... Date_dayofweek Date_dayofweek_no
0  CA-2016-152156 2016-11-08  ...        Tuesday                 1
1  CA-2016-152156 2016-11-08  ...        Tuesday                 1
2  CA-2016-138688 2016-06-12  ...         Sunday                 6
3  US-2015-108966 2015-10-11  ...         Sunday                 6

[4 rows x 11 columns]

In [105]:
df['Date_dayofweek'] = df['Order Date'].dt.day_name()
df.head(4)

         Order ID Order Date  ... Date_dayofweek Date_dayofweek_no
0  CA-2016-152156 2016-11-08  ...        Tuesday                 1
1  CA-2016-152156 2016-11-08  ...        Tuesday                 1
2  CA-2016-138688 2016-06-12  ...         Sunday                 6
3  US-2015-108966 2015-10-11  ...         Sunday                 6

[4 rows x 11 columns]

In [108]:
df['date_of_weekend']=np.where(df['Date_dayofweek'].isin(['Sunday','Saturday']),1,0)
df.head()

         Order ID Order Date  ... Date_dayofweek_no date_of_weekend
0  CA-2016-152156 2016-11-08  ...                 1               0
1  CA-2016-152156 2016-11-08  ...                 1               0
2  CA-2016-138688 2016-06-12  ...                 6               1
3  US-2015-108966 2015-10-11  ...                 6               1
4  US-2015-108966 2015-10-11  ...                 6               1

[5 rows x 12 columns]

### Extract week of the year

In [111]:
df['date_week'] = df['Order Date'].dt.isocalendar().week

In [112]:
df.head()

         Order ID Order Date  ... date_of_weekend date_week
0  CA-2016-152156 2016-11-08  ...               0        45
1  CA-2016-152156 2016-11-08  ...               0        45
2  CA-2016-138688 2016-06-12  ...               1        23
3  US-2015-108966 2015-10-11  ...               1        41
4  US-2015-108966 2015-10-11  ...               1        41

[5 rows x 13 columns]

### Extract Time elapsed between dates

In [113]:
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 3, 23, 14, 16, 19, 805017)

In [114]:
today -df['Order Date']

0      3422 days 14:16:19.805017
1      3422 days 14:16:19.805017
2      3571 days 14:16:19.805017
3      3816 days 14:16:19.805017
4      3816 days 14:16:19.805017
                  ...
9989   4444 days 14:16:19.805017
9990   3312 days 14:16:19.805017
9991   3312 days 14:16:19.805017
9992   3312 days 14:16:19.805017
9993   3245 days 14:16:19.805017
Name: Order Date, Length: 9994, dtype: timedelta64[ns]

In [116]:
(today -df['Order Date']).dt.days

0       3422
1       3422
2       3571
3       3816
4       3816
        ...
9989    4444
9990    3312
9991    3312
9992    3312
9993    3245
Name: Order Date, Length: 9994, dtype: int64

# For Time

In [ ]:
df['Order Date']= pd.to_datetime(df['Order Date'])

In [ ]:
time['hour']=df['Order Date'].dt.hour
time['min']=df['Order Date'].dt.minute
time['sec']=df['Order Date'].dt.second

time.head

### Extract Time part

In [ ]:
time['time']=time['date'].dt.time

### Time Difference

In [ ]:
today- time['date']