In [53]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [54]:
df = pd.read_csv('/Users/prajwalsubedi/Desktop/Data science/Data Sets/titanic.csv',usecols=['Age','Pclass','SibSp','Parch','Survived'])

In [55]:
df.head(5)

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [56]:
df.dropna(inplace=True)

In [57]:
x =df.iloc[:,1:5]
y= df.iloc[:,0]

In [58]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [59]:
x.head()

   Pclass   Age  SibSp  Parch
0       3  22.0      1      0
1       1  38.0      1      0
2       3  26.0      0      0
3       1  35.0      1      0
4       3  35.0      0      0

In [60]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

In [61]:
x['Family_size']=x['SibSp']+x['Parch']+1

In [62]:
 x.head()

   Pclass   Age  SibSp  Parch  Family_size
0       3  22.0      1      0            2
1       1  38.0      1      0            2
2       3  26.0      0      0            1
3       1  35.0      1      0            2
4       3  35.0      0      0            1

In [63]:
def myfunc(num):
    if num ==1:
        return 0 #alone
    elif num>1 and num<=4: 
        return 1 #small family
    else:
        return 2 # large family

In [64]:
myfunc(4)

1

In [65]:
x['Family_type']=x['Family_size'].apply(myfunc)

In [66]:
x.head()

   Pclass   Age  SibSp  Parch  Family_size  Family_type
0       3  22.0      1      0            2            1
1       1  38.0      1      0            2            1
2       3  26.0      0      0            1            0
3       1  35.0      1      0            2            1
4       3  35.0      0      0            1            0

In [67]:
x.drop(columns=['SibSp','Parch','Family_size'])

     Pclass   Age  Family_type
0         3  22.0            1
1         1  38.0            1
2         3  26.0            0
3         1  35.0            1
4         3  35.0            0
..      ...   ...          ...
885       3  39.0            2
886       2  27.0            0
887       1  19.0            0
889       1  26.0            0
890       3  32.0            0

[714 rows x 3 columns]

In [68]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.7031746031746031)